# src/AppBundle/Resources/config/doctrine/Question.orm.yml
AppBundle\Entity\Question:
    type: entity
    table: question
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        description:
            type: string
            length: 100
    oneToMany:
        answers:
            targetEntity: Answer
            mappedBy: question
