# src/AppBundle/Resources/config/doctrine/Test.orm.yml
AppBundle\Entity\Test:
    type: entity
    table: test
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        description:
            type: text
